## Experiment No - 12
## Processing on a dataset and dealing with missing values
## Parth Dahiwade
## 25070123177
## Branch - ENTC A3
## Date - 18-03-2026

In [ ]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'C1':[11,21,np.nan],'C2':[15,np.nan,np.nan],'C3':[10,20,30]})
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [ ]:
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [ ]:
# Boolean Function
df1.isna()

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
df1.notna()

      C1     C2    C3
0   True   True  True
1   True  False  True
2  False  False  True

In [ ]:
# Column wise na values
df1.isna().sum()

C1    1
C2    2
C3    0
dtype: int64

In [ ]:
#NaN Rows are dropped
df1.dropna()

     C1    C2  C3
0  11.0  15.0  10

In [ ]:
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [ ]:
df1.fillna(value='DEFAULT')

        C1       C2  C3
0     11.0     15.0  10
1     21.0  DEFAULT  20
2  DEFAULT  DEFAULT  30

In [ ]:
# Mean values of columns are calculated

df1.fillna(df1.mean())

     C1    C2  C3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [ ]:
# Processing on a dataset - 1
import pandas as pd

data = {
    "Roll No": [101,102,103,104,105],
    "Name": ["John", "Emily", "Michael", "Sarah", "David"],
    "Age": [20,"-",21,20,"22"],
    "Marks":[85,90,"-",88,76],
    "Department":["CSE","IT","CSE","cse","E&TC"],
    "Admission_Date":["2022-01-15","03-06-2023","05-06-2023","07-06-2023","10/06/23"]

}

df = pd.DataFrame(data)

# Save as CSV

df.to_csv("student_data.csv", index=False)

In [ ]:
import pandas as pd
import numpy as np
# Step - 1 Load the dataset

df = pd.read_csv("student_data.csv")

print("Original Data:")
print(df)

Original Data:
   Roll No     Name Age Marks Department Admission_Date
0      101     John  20    85        CSE     2022-01-15
1      102    Emily   -    90         IT     03-06-2023
2      103  Michael  21     -        CSE     05-06-2023
3      104    Sarah  20    88        cse     07-06-2023
4      105    David  22    76       E&TC       10/06/23

In [ ]:
df.replace("-",np.nan,inplace=True)
df

   Roll No     Name  Age Marks Department Admission_Date
0      101     John   20    85        CSE     2022-01-15
1      102    Emily  NaN    90         IT     03-06-2023
2      103  Michael   21   NaN        CSE     05-06-2023
3      104    Sarah   20    88        cse     07-06-2023
4      105    David   22    76       E&TC       10/06/23

In [ ]:
# Step - 2 '-' With NaN to mark missing values

df.replace("-",np.nan, inplace=True)

# Convert columns to numeric where needed
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")

''' When converting data (like strings to datatime),
if some values are invalid or cannot be converted,
insead of throwing an error, it will:
Replace those invalid values with NaT (Not a Time)
'''
df

   Roll No     Name   Age  Marks Department Admission_Date
0      101     John  20.0   85.0        CSE     2022-01-15
1      102    Emily   NaN   90.0         IT     03-06-2023
2      103  Michael  21.0    NaN        CSE     05-06-2023
3      104    Sarah  20.0   88.0        cse     07-06-2023
4      105    David  22.0   76.0       E&TC       10/06/23

In [ ]:
# Step - 3 Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
Roll No           0
Name              0
Age               1
Marks             1
Department        0
Admission_Date    0
dtype: int64

In [ ]:
# Fill the missing age with mean
df["Age"].fillna(df["Age"].mean(), inplace=True)

/tmp/ipykernel_192/2969031484.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)

In [ ]:
# Fill missing marks with median

df["Marks"].fillna(df["Marks"].median(), inplace=True)

/tmp/ipykernel_192/2024059856.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].median(), inplace=True)

In [ ]:
print(df.isnull().sum())

Roll No           0
Name              0
Age               0
Marks             0
Department        0
Admission_Date    0
dtype: int64

In [ ]:
# Step 5 Fix inconsistent text formattig
df["Department"] = df["Department"].str.upper()

In [ ]:
# Step 6 Convert Admission_Date to standard date time format
df["Admission_Date"] = pd.to_datetime(df["Admission_Date"], errors='coerce')

In [ ]:
df

   Roll No     Name    Age  Marks Department Admission_Date
0      101     John  20.00   85.0        CSE     2022-01-15
1      102    Emily  20.75   90.0         IT            NaT
2      103  Michael  21.00   86.5        CSE            NaT
3      104    Sarah  20.00   88.0        CSE            NaT
4      105    David  22.00   76.0       E&TC            NaT

In [ ]:
# Step 7 Show cleaned data
print("\nCleaned Data:")
print(df)

Cleaned Data:
   Roll No     Name    Age  Marks Department Admission_Date
0      101     John  20.00   85.0        CSE     2022-01-15
1      102    Emily  20.75   90.0         IT            NaT
2      103  Michael  21.00   86.5        CSE            NaT
3      104    Sarah  20.00   88.0        CSE            NaT
4      105    David  22.00   76.0       E&TC            NaT

In [ ]:
# Step 8 Save cleaned dataset
df.to_csv("cleaned_student_data.csv",index=False)

print("\nCleaned CSV file saved as cleaned_student_data.csv")

Cleaned CSV file saved as cleaned_student_data.csv

In [ ]:
# Working with missing values on dataset-2
df=pd.read_csv("/Cars93 (2).csv")
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [ ]:
# Imputing the missing value
#1. Luggage Room
df['Luggage.room']=df['Luggage.room'].fillna(df['Luggage.room'].mean())

In [ ]:
# Rear.seat.room
df["Rear.seat.room"]=df["Rear.seat.room"].fillna(df["Rear.seat.room"].mean())

In [ ]:
# .AirBags
df['AirBags']=df['AirBags'].fillna(value=df['AirBags'].mode().values[0])

In [ ]:
# Save cleaned dataset
df.to_csv("cleaned_Cars93.csv",index=False)